title: FITS Matching Camera Fingerprints Subject to Software Noise Pollution
description: The details about FITS algorithm for camera fingerprints matching
show_downloads: false
theme: jekyll-theme-cayman